notifications:
  email:
    recipients:
      - red-data-tools@ml.commit-email.info

sudo: required

services:
  - docker

install:
  - docker build -t red-data-tools/red-arrow-activerecord .

script:
  - docker run red-data-tools/red-arrow-activerecord /bin/sh -c "bundle exec rake"
